# Generated by Django 5.1.3 on 2024-11-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='is_pending',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='rate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
