# Generated by Django 5.1.3 on 2024-11-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rate_is_pending_alter_rate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='is_valid',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
